name: Deploy Hugo to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Debug: Check built files
        run: |
          ls -la public/
          test -f public/index.html || (echo "❌ Missing index.html!" && exit 1)

      - name: Add .nojekyll and CNAME
        run: |
          touch public/.nojekyll
          echo "www.yiptech.com.au" > public/CNAME

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force: true  # 👈 Critical: forces update
