name: Deploy Hugo to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    environment:
      name: github-pages
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Debug: Check built files
        run: |
          ls -la public/
          if [ ! -f public/index.html ]; then
            echo "Error: index.html not found in public/"
            exit 1
          fi

      - name: Add .nojekyll and CNAME
        run: |
          touch public/.nojekyll
          echo "www.yiptech.com.au" > public/CNAME

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force: true
